/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

/**
 *
 * @author cristian
 */
public class VentanaReceptor extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReceptor
     */
    public VentanaReceptor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_recepcion = new javax.swing.JLabel();
        label_trama_recibida = new javax.swing.JLabel();
        jtxf_indicador = new javax.swing.JTextField();
        jtxf_tama_de_datos = new javax.swing.JTextField();
        jtxf_informacion = new javax.swing.JTextField();
        jtxf_indicador_final = new javax.swing.JTextField();
        label_header = new javax.swing.JLabel();
        label_informacion = new javax.swing.JLabel();
        label_trailer = new javax.swing.JLabel();
        label_respuesta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_indicador = new javax.swing.JLabel();
        jtfield_indicador = new javax.swing.JTextField();
        label_ack = new javax.swing.JLabel();
        jtfield_ack = new javax.swing.JTextField();
        label_enq = new javax.swing.JLabel();
        jtfield_enq = new javax.swing.JTextField();
        label_ctr = new javax.swing.JLabel();
        jtfield_ctr = new javax.swing.JTextField();
        label_dat = new javax.swing.JLabel();
        jtfield_dat = new javax.swing.JTextField();
        label_ppt = new javax.swing.JLabel();
        jtfield_ppt = new javax.swing.JTextField();
        label_lpt = new javax.swing.JLabel();
        jtfield_lpt = new javax.swing.JTextField();
        label_num = new javax.swing.JLabel();
        jtfield_num = new javax.swing.JTextField();
        label_informacionRx = new javax.swing.JLabel();
        jtfield_informacion = new javax.swing.JTextField();
        label_indicador2 = new javax.swing.JLabel();
        jtfield_indicador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        label_semantica = new javax.swing.JLabel();
        label_tramade = new javax.swing.JLabel();
        label_estadorecepcion = new javax.swing.JLabel();
        label_mensaje_recibido = new javax.swing.JLabel();
        jtxf_mensaje_recibido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_recepcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_recepcion.setForeground(new java.awt.Color(255, 0, 0));
        label_recepcion.setText("RECEPTOR");

        label_trama_recibida.setText("TRAMA RECIBIDA:");

        jtxf_indicador.setEditable(false);
        jtxf_indicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxf_indicadorActionPerformed(evt);
            }
        });

        jtxf_tama_de_datos.setEditable(false);
        jtxf_tama_de_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxf_tama_de_datosActionPerformed(evt);
            }
        });

        jtxf_informacion.setEditable(false);

        jtxf_indicador_final.setEditable(false);

        label_header.setText("HEADER");

        label_informacion.setText("INFORMACION");

        label_trailer.setText("TRAILER");

        label_respuesta.setText("RESPUESTA:");

        label_indicador.setBackground(new java.awt.Color(0, 0, 0));
        label_indicador.setForeground(new java.awt.Color(255, 0, 51));
        label_indicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_indicador.setText("Indicador");
        label_indicador.setToolTipText("");

        jtfield_indicador.setEditable(false);
        jtfield_indicador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_indicador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfield_indicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfield_indicadorActionPerformed(evt);
            }
        });

        label_ack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ack.setText("ACK");

        jtfield_ack.setEditable(false);
        jtfield_ack.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_enq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_enq.setText("ENQ");

        jtfield_enq.setEditable(false);
        jtfield_enq.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_ctr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ctr.setText("CTR");

        jtfield_ctr.setEditable(false);
        jtfield_ctr.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_dat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dat.setText("DAT");

        jtfield_dat.setEditable(false);
        jtfield_dat.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_ppt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ppt.setText("PPT");

        jtfield_ppt.setEditable(false);
        jtfield_ppt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_lpt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_lpt.setText("LPT");

        jtfield_lpt.setEditable(false);
        jtfield_lpt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_num.setText("NUM");

        jtfield_num.setEditable(false);
        jtfield_num.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_informacionRx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_informacionRx.setText("INFORMACION");

        jtfield_informacion.setEditable(false);
        jtfield_informacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_indicador2.setBackground(new java.awt.Color(0, 0, 0));
        label_indicador2.setForeground(new java.awt.Color(255, 0, 51));
        label_indicador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_indicador2.setText("Indicador");
        label_indicador2.setToolTipText("");

        jtfield_indicador2.setEditable(false);
        jtfield_indicador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_indicador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_semantica.setText("SEMANTICA");

        label_tramade.setText("TRAMA DE ");

        label_estadorecepcion.setText(",TRAMA RECIBIDA CON:");

        label_mensaje_recibido.setText("MENSAJE RECIBIDO:");

        jtxf_mensaje_recibido.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_header)
                            .addComponent(jtxf_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxf_tama_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxf_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxf_indicador_final, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(label_informacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_trailer)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_trama_recibida)
                            .addComponent(label_respuesta))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(label_indicador))
                                    .addComponent(jtfield_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_ack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfield_ack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_enq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfield_enq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfield_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_dat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfield_dat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfield_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfield_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfield_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfield_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_informacionRx, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfield_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(label_recepcion)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(label_semantica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tramade)
                        .addGap(43, 43, 43)
                        .addComponent(label_estadorecepcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label_mensaje_recibido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxf_mensaje_recibido, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label_recepcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_trama_recibida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxf_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxf_tama_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxf_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxf_indicador_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_header)
                    .addComponent(label_informacion)
                    .addComponent(label_trailer))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_respuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_indicador)
                            .addComponent(label_ack)
                            .addComponent(label_enq)
                            .addComponent(label_ctr)
                            .addComponent(label_dat)
                            .addComponent(label_ppt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfield_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_enq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_lpt)
                            .addComponent(label_num)
                            .addComponent(label_informacionRx)
                            .addComponent(label_indicador2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfield_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_semantica)
                    .addComponent(label_tramade)
                    .addComponent(label_estadorecepcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_mensaje_recibido)
                    .addComponent(jtxf_mensaje_recibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxf_tama_de_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxf_tama_de_datosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxf_tama_de_datosActionPerformed

    private void jtxf_indicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxf_indicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxf_indicadorActionPerformed

    private void jtfield_indicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfield_indicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfield_indicadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReceptor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jtfield_ack;
    private javax.swing.JTextField jtfield_ctr;
    private javax.swing.JTextField jtfield_dat;
    private javax.swing.JTextField jtfield_enq;
    private javax.swing.JTextField jtfield_indicador;
    private javax.swing.JTextField jtfield_indicador2;
    private javax.swing.JTextField jtfield_informacion;
    private javax.swing.JTextField jtfield_lpt;
    private javax.swing.JTextField jtfield_num;
    private javax.swing.JTextField jtfield_ppt;
    private javax.swing.JTextField jtxf_indicador;
    private javax.swing.JTextField jtxf_indicador_final;
    private javax.swing.JTextField jtxf_informacion;
    private javax.swing.JTextField jtxf_mensaje_recibido;
    private javax.swing.JTextField jtxf_tama_de_datos;
    private javax.swing.JLabel label_ack;
    private javax.swing.JLabel label_ctr;
    private javax.swing.JLabel label_dat;
    private javax.swing.JLabel label_enq;
    private javax.swing.JLabel label_estadorecepcion;
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_indicador;
    private javax.swing.JLabel label_indicador2;
    private javax.swing.JLabel label_informacion;
    private javax.swing.JLabel label_informacionRx;
    private javax.swing.JLabel label_lpt;
    private javax.swing.JLabel label_mensaje_recibido;
    private javax.swing.JLabel label_num;
    private javax.swing.JLabel label_ppt;
    private javax.swing.JLabel label_recepcion;
    private javax.swing.JLabel label_respuesta;
    private javax.swing.JLabel label_semantica;
    private javax.swing.JLabel label_trailer;
    private javax.swing.JLabel label_trama_recibida;
    private javax.swing.JLabel label_tramade;
    // End of variables declaration//GEN-END:variables
}
