/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import logica.Transmitir;

/**
 *
 * @author cristian
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_transmisor = new javax.swing.JLabel();
        label_msn_tx = new javax.swing.JLabel();
        jtfield_msn_tx = new javax.swing.JTextField();
        jlabel_frames = new javax.swing.JLabel();
        jtfield_frames = new javax.swing.JTextField();
        jlabel_indicador = new javax.swing.JLabel();
        jtfield_indicador = new javax.swing.JTextField();
        jlabel_ack = new javax.swing.JLabel();
        jtfield_ack = new javax.swing.JTextField();
        jlabel_enq = new javax.swing.JLabel();
        jtfield_enq = new javax.swing.JTextField();
        jlabel_ctr = new javax.swing.JLabel();
        jtfield_ctr = new javax.swing.JTextField();
        jlabel_dat = new javax.swing.JLabel();
        jtfield_dat = new javax.swing.JTextField();
        jlabel_ppt = new javax.swing.JLabel();
        jtfield_ppt = new javax.swing.JTextField();
        jlabel_lpt = new javax.swing.JLabel();
        jtfield_lpt = new javax.swing.JTextField();
        jlabel_num = new javax.swing.JLabel();
        jtfield_num = new javax.swing.JTextField();
        jtfield_informacion = new javax.swing.JTextField();
        jlabel_informacion = new javax.swing.JLabel();
        jlabel_indicador2 = new javax.swing.JLabel();
        jtfield_indicador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jcbox_ack = new javax.swing.JCheckBox();
        jcbox_enq = new javax.swing.JCheckBox();
        jcbox_ctr = new javax.swing.JCheckBox();
        jcbox_dat = new javax.swing.JCheckBox();
        jcbox_ppt = new javax.swing.JCheckBox();
        jcbox_lpt = new javax.swing.JCheckBox();
        jlabel_secuencia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtarea_secuencia = new javax.swing.JTextArea();
        jbtn_enviar_tx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_transmisor.setForeground(new java.awt.Color(204, 0, 51));
        label_transmisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_transmisor.setText("TRANSMISOR");

        label_msn_tx.setText("Mensaje a transmitir:");

        jtfield_msn_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfield_msn_txActionPerformed(evt);
            }
        });

        jlabel_frames.setText("Frames:");

        jtfield_frames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfield_framesActionPerformed(evt);
            }
        });

        jlabel_indicador.setBackground(new java.awt.Color(0, 0, 0));
        jlabel_indicador.setForeground(new java.awt.Color(255, 0, 51));
        jlabel_indicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_indicador.setText("Indicador");
        jlabel_indicador.setToolTipText("");

        jtfield_indicador.setEditable(false);
        jtfield_indicador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_indicador.setText("10000001");
        jtfield_indicador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfield_indicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfield_indicadorActionPerformed(evt);
            }
        });

        jlabel_ack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_ack.setText("ACK");

        jtfield_ack.setEditable(false);
        jtfield_ack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_ack.setText("0");

        jlabel_enq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_enq.setText("ENQ");

        jtfield_enq.setEditable(false);
        jtfield_enq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_enq.setText("0");

        jlabel_ctr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_ctr.setText("CTR");

        jtfield_ctr.setEditable(false);
        jtfield_ctr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_ctr.setText("0");

        jlabel_dat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_dat.setText("DAT");

        jtfield_dat.setEditable(false);
        jtfield_dat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_dat.setText("0");

        jlabel_ppt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_ppt.setText("PPT");

        jtfield_ppt.setEditable(false);
        jtfield_ppt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_ppt.setText("0");

        jlabel_lpt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_lpt.setText("LPT");

        jtfield_lpt.setEditable(false);
        jtfield_lpt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_lpt.setText("0");

        jlabel_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_num.setText("NUM");

        jtfield_num.setEditable(false);
        jtfield_num.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_num.setText("0");

        jtfield_informacion.setEditable(false);
        jtfield_informacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlabel_informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_informacion.setText("INFORMACION");

        jlabel_indicador2.setBackground(new java.awt.Color(0, 0, 0));
        jlabel_indicador2.setForeground(new java.awt.Color(255, 0, 51));
        jlabel_indicador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_indicador2.setText("Indicador");
        jlabel_indicador2.setToolTipText("");

        jtfield_indicador2.setEditable(false);
        jtfield_indicador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfield_indicador2.setText("10000001");
        jtfield_indicador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jcbox_ack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouse(evt);
            }
        });
        jcbox_ack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_ackActionPerformed(evt);
            }
        });

        jcbox_enq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_enqActionPerformed(evt);
            }
        });

        jcbox_ctr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_ctrActionPerformed(evt);
            }
        });

        jcbox_dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_datActionPerformed(evt);
            }
        });

        jcbox_ppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_pptActionPerformed(evt);
            }
        });

        jcbox_lpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbox_lptActionPerformed(evt);
            }
        });

        jlabel_secuencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_secuencia.setText("SECUENCIA DE TRAMAS");

        jtarea_secuencia.setEditable(false);
        jtarea_secuencia.setColumns(20);
        jtarea_secuencia.setRows(5);
        jScrollPane1.setViewportView(jtarea_secuencia);

        jbtn_enviar_tx.setText("ENVIAR");
        jbtn_enviar_tx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_enviar_txActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_msn_tx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfield_msn_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabel_frames)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfield_frames, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jlabel_indicador))
                                            .addComponent(jtfield_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlabel_ack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfield_ack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jcbox_ack, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlabel_enq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfield_enq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jcbox_enq)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfield_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbox_ctr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlabel_dat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfield_dat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfield_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbox_dat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbox_ppt)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbox_lpt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfield_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlabel_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfield_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfield_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfield_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(label_transmisor, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jbtn_enviar_tx))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jlabel_secuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_transmisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_msn_tx)
                    .addComponent(jtfield_msn_tx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_frames)
                    .addComponent(jtfield_frames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel_indicador)
                            .addComponent(jlabel_ack)
                            .addComponent(jlabel_enq)
                            .addComponent(jlabel_ctr)
                            .addComponent(jlabel_dat)
                            .addComponent(jlabel_ppt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfield_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_enq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ctr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_ppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbox_ack)
                                        .addComponent(jcbox_ctr, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jcbox_dat, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jcbox_ppt, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jcbox_enq)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel_lpt)
                            .addComponent(jlabel_num)
                            .addComponent(jlabel_informacion)
                            .addComponent(jlabel_indicador2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfield_lpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfield_indicador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbox_lpt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_enviar_tx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel_secuencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfield_msn_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfield_msn_txActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfield_msn_txActionPerformed

    private void jcbox_ackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_ackActionPerformed
        int aux = Integer.parseInt(jtfield_ack.getText());
        if(aux==0){
            jtfield_ack.setText("1");
        }else{
            jtfield_ack.setText("0");
        }
        
    }//GEN-LAST:event_jcbox_ackActionPerformed

    private void mouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse
        // TODO add your handling code here:
    }//GEN-LAST:event_mouse

    private void jbtn_enviar_txActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_enviar_txActionPerformed
        Transmitir transmisor = new Transmitir();
        transmisor.setInformacion(jtfield_msn_tx.getText());
        transmisor.setAck(Integer.parseInt(jtfield_ack.getText()));
        transmisor.setEnq(Integer.parseInt(jtfield_enq.getText()));
        transmisor.setCtr(Integer.parseInt(jtfield_ctr.getText()));
        transmisor.setDat(Integer.parseInt(jtfield_dat.getText()));
        transmisor.setPpt(Integer.parseInt(jtfield_ppt.getText()));
        transmisor.setLpt(Integer.parseInt(jtfield_lpt.getText()));
        transmisor.construir_Frame();
        transmisor.enviar();
    }//GEN-LAST:event_jbtn_enviar_txActionPerformed

    private void jcbox_enqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_enqActionPerformed
        int aux = Integer.parseInt(jtfield_enq.getText());
        if(aux==0){
            jtfield_enq.setText("1");
        }else{
            jtfield_enq.setText("0");
        }
    }//GEN-LAST:event_jcbox_enqActionPerformed

    private void jcbox_ctrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_ctrActionPerformed
        int aux = Integer.parseInt(jtfield_ctr.getText());
        if(aux==0){
            jtfield_ctr.setText("1");
        }else{
            jtfield_ctr.setText("0");
        }
    }//GEN-LAST:event_jcbox_ctrActionPerformed

    private void jcbox_datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_datActionPerformed
        int aux = Integer.parseInt(jtfield_dat.getText());
        if(aux==0){
            jtfield_dat.setText("1");
        }else{
            jtfield_dat.setText("0");
        }
    }//GEN-LAST:event_jcbox_datActionPerformed

    private void jcbox_pptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_pptActionPerformed
        int aux = Integer.parseInt(jtfield_ppt.getText());
        if(aux==0){
            jtfield_ppt.setText("1");
        }else{
            jtfield_ppt.setText("0");
        }
    }//GEN-LAST:event_jcbox_pptActionPerformed

    private void jcbox_lptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbox_lptActionPerformed
        int aux = Integer.parseInt(jtfield_lpt.getText());
        if(aux==0){
            jtfield_lpt.setText("1");
        }else{
            jtfield_lpt.setText("0");
        }
    }//GEN-LAST:event_jcbox_lptActionPerformed

    private void jtfield_framesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfield_framesActionPerformed
        jtfield_num.setText(jtfield_frames.getText());
    }//GEN-LAST:event_jtfield_framesActionPerformed

    private void jtfield_indicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfield_indicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfield_indicadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtn_enviar_tx;
    private javax.swing.JCheckBox jcbox_ack;
    private javax.swing.JCheckBox jcbox_ctr;
    private javax.swing.JCheckBox jcbox_dat;
    private javax.swing.JCheckBox jcbox_enq;
    private javax.swing.JCheckBox jcbox_lpt;
    private javax.swing.JCheckBox jcbox_ppt;
    private javax.swing.JLabel jlabel_ack;
    private javax.swing.JLabel jlabel_ctr;
    private javax.swing.JLabel jlabel_dat;
    private javax.swing.JLabel jlabel_enq;
    private javax.swing.JLabel jlabel_frames;
    private javax.swing.JLabel jlabel_indicador;
    private javax.swing.JLabel jlabel_indicador2;
    private javax.swing.JLabel jlabel_informacion;
    private javax.swing.JLabel jlabel_lpt;
    private javax.swing.JLabel jlabel_num;
    private javax.swing.JLabel jlabel_ppt;
    private javax.swing.JLabel jlabel_secuencia;
    private javax.swing.JTextArea jtarea_secuencia;
    private javax.swing.JTextField jtfield_ack;
    private javax.swing.JTextField jtfield_ctr;
    private javax.swing.JTextField jtfield_dat;
    private javax.swing.JTextField jtfield_enq;
    private javax.swing.JTextField jtfield_frames;
    private javax.swing.JTextField jtfield_indicador;
    private javax.swing.JTextField jtfield_indicador2;
    private javax.swing.JTextField jtfield_informacion;
    private javax.swing.JTextField jtfield_lpt;
    private javax.swing.JTextField jtfield_msn_tx;
    private javax.swing.JTextField jtfield_num;
    private javax.swing.JTextField jtfield_ppt;
    private javax.swing.JLabel label_msn_tx;
    private javax.swing.JLabel label_transmisor;
    // End of variables declaration//GEN-END:variables

    /** mostrar_mensajes
     *  Este metodo se encarga de crear los mensajes para mostrar en la ventana
     *  principal.
     */
    public void mostrar_mensajes(){
        if(jtfield_ack.getText()=="1"){
            
        }
    }
}
